/***************************************************
 * semdiag: draw SEM path diagram interactively    *
 * Authors: Yujiao Mai, Zhiyong Zhang, Ke-Hai Yuan *
 * Copyright 2015-2015, psychstat.org              *
 * Licensed under the MIT License (MIT)            *
 * Current software version 1.0                    *
 * Support email for questions zzhang4@nd.edu      *
 *                             ymai@nd.edu         *
 ***************************************************/
 var default_RADIUSH = 20,
 default_RADIUSV = 20,
 nodeInitialPos = { x: 3 * default_RADIUSH, y: 3 * default_RADIUSV },
 nodeInitialPos_rect = { x: 3 * default_RADIUSH, y: 3 * default_RADIUSV },
 nodeInitialPos_ellipse = { x: 6 * default_RADIUSH, y: 3 * default_RADIUSV },
 default_selfcurve_LR = (3.2 * default_RADIUSH) / 2,
 newr_DISCOUNT = 0.2,
 cPr = 3,
 selfpathANGLE_default = 0.225 * Math.PI,
 selfpathTHETA_default = (7 / 4) * Math.PI,
 defaultFONTSIZE = 12,
 default_strokeWIDTH = 1,
 defaultFillCOLOR = "WHITE",
 activatedCOLOR = "#FF1493",
 backgroundCOLOR = "WHITE",
 defaultCOLOR = "BLACK",
 COLORlist = ["BLACK", "RED", "BLUE", "GREEN"],
 linkingtoArrowTYPE = "uni",
 linkingtoLineType = "straight",
 Nt = 1e3,
 sc_rp = 1e3,
 diagName = "",
 nodes = [],
 edges = [],
 edges_tangents = [],
 notes = [],
 numRec = 0,
 numElli = 0,
 numTri = 0,
 numNode = 0,
 numEdge = 0,
 numnote = 0,
 Nodecurrent_IdNUM = 0,
 Elli_current_TitleNUM = 0,
 Rec_current_TitleNUM = 0,
 Edgecurrent_IdNUM = 0,
 Notecurrent_IdNUM = 0,
 newnodeInitialPos_rect = { x: nodeInitialPos_rect.x, y: nodeInitialPos_rect.y },
 newnodeInitialPos_ellipse = { x: nodeInitialPos_ellipse.x, y: nodeInitialPos_ellipse.y },
 loopTagger_newnode = 5,
 theTriangle = null,
 ellipsenodes,
 rectnodes,
 trianglenodes,
 w = 1500,
 h = 1500,
 svgstatus = {
     svgondragged: 0,
     nodeondragged: 0,
     nodeselected: 0,
     edgeselected: 0,
     labelselected: 0,
     noteselected: 0,
     linkingto: 0,
     texting: 0,
     multipleselecting: 0,
     multidraging: 0,
     IsShowLabels: !0,
     IsShowGrid: !0,
     stackdeep: 0,
     mathjaxrun: !1,
 },
 svgdragline = { x0: 0, y0: 0, x1: 0, y1: 0 },
 multipleselectframe = { x: 0, y: 0, width: 0, height: 0 },
 predraggedindex = -1,
 justmousedownnodeindex = -1,
 justmousedownedgeindex = -1,
 justmousedownnoteindex = -1,
 linkinginitialindex = -1,
 linkingtargetindex = -1,
 mouseLastclickOBJETid,
 mouseCurrentclickOBJETid,
 mouseLastclicktime,
 mouseCurrentclicktime,
 selectednodeindex = -1,
 selectededgeindex = -1,
 selectednoteindex = -1,
 selectednodeindexes = [],
 selectededgeindexes = [],
 selectednoteindexes = [],
 selcetedBTNID = "",
 mysvgG,
 mysvgG_foreignObject,
 pathGs,
 handleGs,
 nodeGs,
 ellipseGs,
 rectGs,
 triangleGs,
 paths,
 handlePs,
 labelTs,
 ellipses,
 rects,
 triangles,
 nodetexts,
 noteTs,
 current_RADIUSH = default_RADIUSH,
 current_RADIUSV = default_RADIUSV,
 current_selfcurve_LR = default_selfcurve_LR,
 current_selfpathTHETA = selfpathTHETA_default,
 current_FONTSIZE = defaultFONTSIZE,
 current_strokeWIDTH = default_strokeWIDTH,
 current_FillCOLOR = defaultFillCOLOR,
 current_COLOR = defaultCOLOR;
